version: '3'

services:

  mysql-main-1:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql/mysql.env
    hostname: "mysql-main-1"
    container_name: "mysql-main-1"
    volumes:
      - ./mysql/conf/mysql_main_1.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./mysql/sql:/sql
      - dump-volume:/dump-vol

  mysql-main-2:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql/mysql.env
    hostname: "mysql-main-2"
    container_name: "mysql-main-2"
    volumes:
      - ./mysql/conf/mysql_main_2.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./mysql/sql:/sql
      - dump-volume:/dump-vol

  mysql-main-3:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql/mysql.env
    hostname: "mysql-main-3"
    container_name: "mysql-main-3"
    volumes:
      - ./mysql/conf/mysql_main_3.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./mysql/sql:/sql
      - dump-volume:/dump-vol

  mysql-misc-a:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql/mysql.env
    hostname: "mysql-misc-a"
    container_name: "mysql-misc-a"
    volumes:
      - ./mysql/conf/mysql_misc_a.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./mysql/sql:/sql
      - dump-volume:/dump-vol

  mysql-misc-b:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql/mysql.env
    hostname: "mysql-misc-b"
    container_name: "mysql-misc-b"
    volumes:
      - ./mysql/conf/mysql_misc_b.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./mysql/sql:/sql
      - dump-volume:/dump-vol

  orch-1:
    build:
      context: ./orch
      dockerfile: Dockerfile
    hostname: "orch-1"
    ports:
      - 3111:3000
    volumes:
      - ./orch/conf-1.json:/usr/local/orchestrator/conf/orchestrator.conf.json

  orch-2:
    build:
      context: ./orch
      dockerfile: Dockerfile
    hostname: "orch-2"
    ports:
      - 3112:3000
    volumes:
      - ./orch/conf-2.json:/usr/local/orchestrator/conf/orchestrator.conf.json

  orch-3:
    build:
      context: ./orch
      dockerfile: Dockerfile
    hostname: "orch-3"
    ports:
      - 3113:3000
    volumes:
      - ./orch/conf-3.json:/usr/local/orchestrator/conf/orchestrator.conf.json


volumes:
     dump-volume: