version: '3'
services:
  mysql-master:
    image: mysql:5.7
    env_file:
      - ./mysql.env
    hostname: "mysql-master"
    container_name: "mysql-master"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./orch.sql:/orch.sql
      - ./repl_user.sql:/repl_user.sql
    networks:
      - overlay

  mysql-slave:
    image: mysql:5.7
    env_file:
      - ./mysql.env
    hostname: "mysql-slave"
    container_name: "mysql-slave"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql-master
    volumes:
      - ./slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./orch.sql:/orch.sql
      - ./repl_user.sql:/repl_user.sql
    networks:
      - overlay

  orch:
    build:
      context: ./orch
      dockerfile: Dockerfile
    hostname: "orch"
    container_name: "orch"
    ports:
      - 3003:3000
    volumes:
      - ./orch/conf.json:/usr/local/orchestrator/orchestrator.conf.json
    networks:
      - overlay

networks:
  overlay:

