version: '3'

services:

  mysql-main-1:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql.env
    hostname: "mysql-main-1"
    container_name: "mysql-main-1"
    volumes:
      - ./main-1/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./orch.sql:/orch.sql
      - ./repl_main.sql:/repl.sql

  mysql-main-2:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql.env
    hostname: "mysql-main-2"
    container_name: "mysql-main-2"
    volumes:
      - ./main-2/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./orch.sql:/orch.sql
      - ./repl_main.sql:/repl.sql

  mysql-main-3:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql.env
    hostname: "mysql-main-3"
    container_name: "mysql-main-3"
    volumes:
      - ./main-3/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./orch.sql:/orch.sql
      - ./repl_main.sql:/repl.sql

  mysql-misc-a:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql.env
    hostname: "mysql-misc-a"
    container_name: "mysql-misc-a"
    volumes:
      - ./misc-a/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./orch.sql:/orch.sql
      - ./repl_misc.sql:/repl.sql

  mysql-misc-b:
    image: "${MYSQL_IMAGE}"
    env_file:
      - ./mysql.env
    hostname: "mysql-misc-b"
    container_name: "mysql-misc-b"
    volumes:
      - ./misc-b/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./orch.sql:/orch.sql
      - ./repl_misc.sql:/repl.sql

  orch:
    build:
      context: ./orch
      dockerfile: Dockerfile
    hostname: "orch"
    ports:
      - 3003:3000
    volumes:
      - ./orch/conf.json:/usr/local/orchestrator/orchestrator.conf.json
